BASE_TASK_CONFIG_PATH: habitat_extensions/config/rxr_vlnce_english_task.yaml
TRAINER_NAME: recollect_trainer
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/rxr_cma_en
CHECKPOINT_FOLDER: data/checkpoints/rxr_cma_en
EVAL_CKPT_PATH_DIR: data/checkpoints/rxr_cma_en
RESULTS_DIR: data/checkpoints/rxr_cma_en/evals

INFERENCE:
  SPLIT: test_challenge
  LANGUAGES: [en-US, en-IN]
  SAMPLE: True
  USE_CKPT_CONFIG: False
  CKPT_PATH: data/checkpoints/ckpt.0.pth  # REPLACE THIS
  PREDICTIONS_FILE: rxr_cma_en_test_challenge.jsonl
  FORMAT: rxr

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  LANGUAGES: [en-US, en-IN]
  EPISODE_COUNT: -1
  SAMPLE: True

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ResizeShortestEdge, CenterCropperPerSensor]

IL:
  batch_size: 3
  epochs: 15
  inflection_weight_coef: 1.9

  RECOLLECT_TRAINER:
    preload_size: 30
    preload_trajectories_file: False
    trajectories_file: data/trajectories_dirs/rxr_en_guide_trim250/trajectories.json.gz
    max_traj_len: 250  # 1.3% of episodes in the English training split are above 250

MODEL:
  policy_name: CMAPolicy
  INSTRUCTION_ENCODER:
    bidirectional: True
    sensor_uuid: rxr_instruction
    embedding_size: 768
